<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="LiteDB">
      <HintPath>..\lib\bin\LiteDB\release_net8.0\LiteDB.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
