<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>ConsoleApp1</AssemblyName><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><Reference Include="LiteDB"><HintPath>__WORKSPACE__/artifacts_temp/audit-explorer/LiteDB/bin/Release/net8.0/LiteDB.dll</HintPath></Reference></ItemGroup></Project>